[project]
name = "citadel-mcp"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.3.3",
    "mcp[cli]>=1.8.1",
    "requests>=2.32.3",
]
